name: biscuit
on: push

jobs:
  tests:
    strategy:
      matrix:
        dir:
          [
            "biscuit-schema",
            "biscuit-format",
            "biscuit-datalog",
            "biscuit",
            "biscuit-samples",
          ]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.12.0
      - name: zig build test
        working-directory: "./${{matrix.dir}}"
        run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.12.0
      - run: zig fmt --check .
